### ISSUE TITLE
run error in mfr.py

### ISSUE THREAD

**Issue by zhaoxin111** [Connor323/Eye-Fundus-Image-Segmentation#1]
when I run the mfr.com,error occur me.I don't know why.

Traceback (most recent call last):
  File "E:\JetBrains\PyCharm 2017.3.3\helpers\pydev\pydev_run_in_console.py", line 53, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\JetBrains\PyCharm 2017.3.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/pycharmWorkSpace/Eye-Fundus-Image-Segmentation-master/mfr.py", line 267, in <module>
    num[label[y][x]] += 1
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

when I debug ,I find label[y][x]-1=-1 cause the error.How can I fix the bug?

**Comment by Connor323** [comment]
Hi, 

It seems I forgot to convert float to integer when querying the array. You can fix it by changing num[label[y][x]] to num[int(label[y][x])] or pull the newer version I just commited. 

Best wishes,

**Comment by zhaoxin111** [comment]
Thank you very much! It is a nice job.
